# Fazer AI - Bypass Settings
CHATWOOT_EDITION=enterprise
ENABLE_ACCOUNT_LEVEL_FEATURE_FLAGS=true
LIMITS_INBOXES=0
LIMITS_USERS=0
LIMITS_TEAMS=0
LIMITS_CAMPAIGNS=0
LIMITS_AUTOMATIONS=0
LIMITS_AGENT_BOTS=0
LIMITS_CANNED_RESPONSES=0
LIMITS_MACROS=0
LIMITS_SLA_POLICIES=0
LIMITS_WEBHOOKS=0
LIMITS_ROUTING_RULES=0
LIMITS_HELP_CENTER=0
